name: test
on:
  push:
  pull_request:

permissions:
  checks: write

jobs:
  test:
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Install Fish Shell
        run: sudo apt update -y && sudo apt install -y fish
      - uses: actions/checkout@v3
      - name: Download Oh-My-Fish installer
        run: curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install > install
      - name: Install Oh-My-Fish
        run: fish install --noninteractive
      - name: Install plugin from current working directory
        run: fish -c "omf install (pwd)"
      - name: Run tests
        run: fish -l test/bootstrap.fish
